/*
 * File: app/store/EveTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.EveTreeStore', {
    extend: 'Ext.data.TreeStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            autoSync: true,
            storeId: 'MyTreeStore1',
            root: {
                expanded: true
            },
            proxy: {
                type: 'ajax',
                url: 'http://localhost/sencha/EveItemBrowser/data/eve.json',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'marketGroupID'
                },
                {
                    name: 'parentGroupID'
                },
                {
                    name: 'marketGroupName'
                },
                {
                    mapping: '',
                    name: 'nameText'
                },
                {
                    name: 'descText'
                },
                {
                    name: 'description'
                }
            ],
            sorters: {
                property: 'marketGroupName'
            }
        }, cfg)]);
    }
});